#!/usr/bin/env python3
"""Regenerate the compact explicit certificates shipped in the repository."""

from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from ep776_check import check_antichain_profile  # noqa: E402
from ep776_padding import free_sets  # noqa: E402
from ep776_profile import construct, core_profile  # noqa: E402


def render_member(member: frozenset[int]) -> str:
    return "{" + ",".join(str(element + 1) for element in sorted(member)) + "}"


def family_text(n: int, r: int, family: dict[int, list[frozenset[int]]]) -> str:
    lines = [
        "Explicit lower-bound certificate for g(27,11) >= 23.",
        "Generated by tools/generate_certificates.py using the colex construction.",
        "Verify with: python3 tests/verify_r11.py",
        "",
        f"A construction showing that for r={r} and n={n}, one has g(n,r)>=23:",
        "",
        f"Layers used: {sorted(family)}",
        "",
    ]
    for level in sorted(family):
        rendered = ", ".join(render_member(member) for member in family[level])
        lines.append(f"Layer {level:2d}: {rendered}")
    lines.append("")
    return "\n".join(lines)


def core_text(
    q: int,
    r: int,
    core: dict[int, list[frozenset[int]]],
    free: list[frozenset[int]],
    total_free: int,
) -> str:
    lines = [
        "Explicit base-core certificate for the r=11 padding construction.",
        "Elements are numbered 1 through 16.",
        f"The core has {sum(map(len, core.values()))} sets and {total_free} free 12-sets.",
        f"The first {len(free)} free 12-sets are listed after the core.",
        "Verify with: python3 tests/verify_r11.py",
        "",
    ]
    for level in sorted(core):
        rendered = ", ".join(render_member(member) for member in core[level])
        lines.append(f"Core layer {level:2d}: {rendered}")
    lines.append("")
    for index, member in enumerate(free, start=1):
        lines.append(f"Free 12-set {index:2d}: {render_member(member)}")
    lines.append("")
    return "\n".join(lines)


def main() -> None:
    n, r = 27, 11
    profile = {i: r for i in range(2, 25)}
    family = construct(n, profile)
    if family is None:
        raise SystemExit("23-level profile unexpectedly infeasible")
    errors = check_antichain_profile(family, n, r, set(profile))
    if errors:
        raise SystemExit(f"generated family failed independent checking: {errors[:3]}")

    output = ROOT / "certificates" / "r11_n27_23_levels.txt"
    output.write_text(family_text(n, r, family), encoding="utf-8")
    print(f"wrote {output.relative_to(ROOT)} ({sum(map(len, family.values()))} sets)")

    q, s = 16, 13
    core = construct(q, core_profile(s, r))
    if core is None:
        raise SystemExit("r=11 base core unexpectedly infeasible")
    errors = check_antichain_profile(core, q, r, set(range(2, s + 1)))
    if errors:
        raise SystemExit(f"generated core failed independent checking: {errors[:3]}")
    all_free = free_sets(core, q, 12, 10**9)
    if len(all_free) != 88:
        raise SystemExit(f"expected 88 free 12-sets, found {len(all_free)}")
    core_output = ROOT / "certificates" / "r11_core_and_free_sets.txt"
    core_output.write_text(
        core_text(q, r, core, all_free[:r], len(all_free)),
        encoding="utf-8",
    )
    print(
        f"wrote {core_output.relative_to(ROOT)} "
        f"({sum(map(len, core.values()))} core sets, {r} listed free sets)"
    )


if __name__ == "__main__":
    main()
