#!/usr/bin/env python3
from __future__ import annotations
import sys
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1]
sys.path.insert(0,str(ROOT/'src'))
from ep776_profile import construct,core_profile,full_profile

def fmt(s): return '{'+','.join(str(x+1) for x in sorted(s))+'}'
def frees(r):
 q=r+5
 return [frozenset(set(range(q))-{0,j,q-2,q-1}) for j in range(3,q-2)]
def main():
 cert=ROOT/'certificates'
 lines=['Explicit full-profile witnesses at n=2r+5 for every r=4,...,10.','Generated by the canonical colex construction.','Verify with: python3 verification/verify_small_r_exact.py','']
 for r in range(4,11):
  n=2*r+5; fam=construct(n,full_profile(n,r)); assert fam
  lines += [f'A construction showing that for r={r} and n={n}, one has g(n,r)=n-3:','',f'Layers used: {list(range(2,n-1))}','']
  for level in range(2,n-1): lines.append(f'Layer {level:2d}: '+', '.join(fmt(s) for s in fam[level]))
  lines.append('')
 (cert/'small_r_full_witnesses_r4_to_10.txt').write_text('\n'.join(lines),encoding='utf-8')
 lines=['Canonical base cores and explicit persistent free sets for r=4,...,10.','For each r: q=r+5, s=r+2; the core has r sets on every level 2..s.','The listed free sets have size s-1=r+1 and contain no core member.','Verify with: python3 verification/verify_small_r_exact.py','']
 for r in range(4,11):
  q,s=r+5,r+2; core=construct(q,core_profile(s,r)); assert core
  lines.append(f'=== r={r} q={q} s={s} ===')
  for level in range(2,s+1): lines.append(f'Core layer {level:2d}: '+', '.join(fmt(x) for x in core[level]))
  lines.append(f'Free {s-1}-sets: '+', '.join(fmt(x) for x in frees(r))); lines.append('')
 (cert/'small_r_cores_and_free_sets_r4_to_10.txt').write_text('\n'.join(lines),encoding='utf-8')
 print('generated',*(p.name for p in cert.glob('small_r_*')))
if __name__=='__main__': main()
